// Code generated by command: go run asm.go -out primitivefuncs_amd64.s -stubs primitivefuncs.go. DO NOT EDIT.

package bls

// Finds a + b * c + carry and returns the result and the carry.
func MACWithCarry(a uint64, b uint64, c uint64, carry uint64) (uint64, uint64)

// Finds a - b - borrow and returns the result and the borrow.
func SubWithBorrow(a uint64, b uint64, borrow uint64) (uint64, uint64)

// Finds a + b + carry and returns the result and the borrow.
func AddWithCarry(a uint64, b uint64, carry uint64) (uint64, uint64)
