package bls

// This file is for assembly functions that are not able
// to be generated by Avo.

// MultiplyFQRepr multiplies two FQRepr values together.
func MultiplyFQRepr(a, b [6]uint64) (hi [6]uint64, lo [6]uint64)

func MontReduce(hi, lo [6]uint64) (out [6]uint64)

func AddWithCarry(a, b, carry uint64) (uint64, uint64)

func SubWithBorrow(a, b, borrow uint64) (uint64, uint64)

func MACWithCarry(a, b, c, carry uint64) (uint64, uint64)
